"""
Django settings for ToolRadar project.

Generated by 'django-admin startproject' using Django 5.2.6.
Modified for ToolRadar with Wagtail CMS integration.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-s8oiujk4o_@%c106*^_$i5zqfl-w6__ya3k^ua(gs#(7^0r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # Django contrib apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # 数値フォーマット用
    
    # Wagtail apps
    'wagtail.contrib.forms',
    'wagtail.contrib.settings',  # Site Settings
    'wagtail.api.v2',  # Wagtail API for headless preview
    'wagtail.contrib.redirects',
    'wagtail.contrib.table_block',  # TableBlock support
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',
    
    'modelcluster',
    'taggit',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',
    'import_export',
    'drf_spectacular',
    
    # Wagtail extensions
    'wagtail_modeladmin',
    'wagtailcache',
    'wagtailmetadata',
    'wagtail_headless_preview',  # Headless preview support
    
    # Development tools
    'django_extensions',
    'debug_toolbar',
    
    # Local apps
    'apps.core',
    'tools',
    'blog',
    'tags',
    'apps.asp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'toolradar'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('DATABASE_HOST', 'db'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}


# Cache Configuration (Redis)
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

# ローカル翻訳ファイルのパス
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========================================
# Wagtail Settings
# ========================================

WAGTAIL_SITE_NAME = 'ToolRadar'
WAGTAILADMIN_BASE_URL = 'http://localhost:8000'

# Wagtail cache
WAGTAIL_CACHE = True
WAGTAIL_CACHE_BACKEND = 'default'

# Search backend
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.database',
    }
}

# Wagtail Admin言語設定
WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ('ja', '日本語'),
    ('en', 'English'),
]

# RichText features設定
# 注：これらはWagtailがデフォルトで認識するfeatures
# カスタムfeaturesを追加する場合はwagtail_hooksで登録が必要
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'wagtail.admin.rich_text.DraftailRichTextArea',
        'OPTIONS': {
            'features': [
                'h2', 'h3', 'h4',
                'bold', 'italic',
                'ol', 'ul',
                'link', 'document-link',
                'hr',
                'code',
                'superscript', 'subscript',
                'strikethrough',
                'blockquote',
            ]
        }
    }
}

# ========================================
# Wagtail Headless Preview Settings
# ========================================

WAGTAIL_HEADLESS_PREVIEW = {
    # Next.jsフロントエンドのURL
    "CLIENT_URLS": {
        "default": os.getenv('NEXT_PUBLIC_URL', 'http://localhost:3000'),
    },
    # プレビュー時はリダイレクト（Wagtail 7.1+推奨）
    "REDIRECT_ON_PREVIEW": True,
    # トレーリングスラッシュの強制を無効化
    "ENFORCE_TRAILING_SLASH": False,
}


# ========================================
# Django REST Framework Settings
# ========================================

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # レート制限設定（スパム対策）
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # 匿名ユーザー全体の制限
        'contact_burst': '3/min',  # お問い合わせ: 短時間の連続送信制限
        'contact_sustained': '10/hour',  # お問い合わせ: 長期的なスパム制限
    },
}

# DRF Spectacular (OpenAPI/Swagger)
SPECTACULAR_SETTINGS = {
    'TITLE': 'ToolRadar API',
    'DESCRIPTION': 'API for ToolRadar - Trading Tools Curation Platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ========================================
# CORS Settings (for Next.js frontend)
# ========================================

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CORS_ALLOW_CREDENTIALS = True


# ========================================
# Development Tools
# ========================================

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
}


# ========================================
# Logging Configuration
# ========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'scheduler_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'scheduler.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'tools': {
            'handlers': ['console', 'scheduler_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apscheduler': {
            'handlers': ['console', 'scheduler_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ==============================================================================
# EMAIL SETTINGS
# ==============================================================================

# デフォルトの送信元メールアドレス
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@toolradar.jp')

# 開発環境と本番環境でバックエンドを切り替え
if DEBUG:
    # 開発環境: コンソールに出力（実際には送信しない）
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # 本番環境: SMTP経由で実際にメール送信
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# 管理者への通知メール設定
# mail_admins()で使用される
ADMINS = [
    ('ToolRadar Admin', os.getenv('ADMIN_EMAIL', 'admin@toolradar.jp')),
]

# サーバーエラー時の送信元
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'server@toolradar.jp')

# メール件名のプレフィックス（エラー通知等）
EMAIL_SUBJECT_PREFIX = '[ToolRadar] '


# ==============================================================================
# GOOGLE reCAPTCHA v3 SETTINGS
# ==============================================================================

# Google reCAPTCHA v3シークレットキー
# 取得先: https://www.google.com/recaptcha/admin
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')

# reCAPTCHA検証エンドポイント
RECAPTCHA_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify'

# reCAPTCHAスコア閾値（0.0-1.0、1.0が最も人間らしい）
# 0.5未満のリクエストをスパムとして拒否
RECAPTCHA_SCORE_THRESHOLD = 0.5

