# Generated by Django 5.2.6 on 2025-11-25 00:39

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(verbose_name='本文')),
                ('show_in_footer', models.BooleanField(default=True, help_text='チェックを入れるとフッターリンクに表示されます', verbose_name='フッターに表示')),
                ('show_disclaimer', models.BooleanField(default=True, help_text='ページ下部に免責事項を表示', verbose_name='免責事項を表示')),
            ],
            options={
                'verbose_name': '基本ページ',
                'verbose_name_plural': '基本ページ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='フォームの上部に表示される説明文', verbose_name='フォーム説明')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, default='<p>お問い合わせありがとうございます。<br>内容を確認の上、折り返しご連絡させていただきます。</p>', verbose_name='送信完了メッセージ')),
            ],
            options={
                'verbose_name': 'お問い合わせページ',
                'verbose_name_plural': 'お問い合わせページ',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='core.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ToolRadar', max_length=100, verbose_name='サイト名')),
                ('site_description', models.TextField(default='FX・株式・仮想通貨のトレーディングツール総合情報サイト', verbose_name='サイト説明')),
                ('operator_name', models.CharField(default='ToolRadar事務局', help_text='匿名運営のため、個人名は非公開', max_length=100, verbose_name='運営者名')),
                ('twitter_url', models.URLField(blank=True, help_text='例: https://twitter.com/toolradar', verbose_name='Twitter（X）URL')),
                ('google_adsense_id', models.CharField(blank=True, help_text='例: ca-pub-1234567890123456', max_length=50, verbose_name='Google AdSense ID')),
                ('google_analytics_id', models.CharField(blank=True, help_text='例: G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('disclaimer_text', models.TextField(blank=True, default='※投資は元本保証がございません。リスクを理解した上でご利用ください。', help_text='サイト全体で表示される短い免責事項', verbose_name='免責事項（短文）')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'サイト設定',
            },
        ),
    ]
