# Generated by Django 5.2.6 on 2025-11-25 02:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, default='', verbose_name='送信完了メッセージ'),
        ),
    ]
