# Generated by Django 5.2.6 on 2025-11-25 02:43

import json
import uuid
import wagtail.fields
from django.db import migrations


def convert_richtext_to_streamfield(apps, schema_editor):
    """RichTextFieldのデータをStreamField形式に変換"""
    BasicPage = apps.get_model('core', 'BasicPage')
    
    for page in BasicPage.objects.all():
        if page.body:
            # 既存のHTML文字列をStreamField JSON形式に変換
            streamfield_data = json.dumps([{
                "type": "rich_text",
                "value": page.body,
                "id": str(uuid.uuid4())[:8]
            }])
            page.body = streamfield_data
            page.save()


def reverse_migration(apps, schema_editor):
    """StreamFieldからRichTextFieldに戻す"""
    BasicPage = apps.get_model('core', 'BasicPage')
    
    for page in BasicPage.objects.all():
        if page.body:
            try:
                data = json.loads(page.body)
                if data and len(data) > 0:
                    page.body = data[0].get('value', '')
                    page.save()
            except (json.JSONDecodeError, KeyError):
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactpage_thank_you_text'),
    ]

    operations = [
        # 1. まずデータを変換
        migrations.RunPython(convert_richtext_to_streamfield, reverse_migration),
        
        # 2. フィールドタイプを変更
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('raw_html', 1)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link', 'hr'], 'help_text': 'WYSIWYGエディタで編集', 'label': 'リッチテキスト'}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'HTMLコードを直接入力（上級者向け）', 'label': 'HTML直接入力'})}, verbose_name='本文'),
        ),
    ]