# Generated by Django 5.2.6 on 2025-12-04 02:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_basicpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.fields.StreamField([('rich_text', 0), ('raw_html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link'], 'help_text': 'WYSIWYG エディタで編集', 'label': 'リッチテキスト'}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '<small>タグなどHTMLを直接入力（上級者向け）', 'label': 'HTML直接入力'})}, verbose_name='フォーム説明'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.StreamField([('rich_text', 0), ('raw_html', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link'], 'help_text': 'WYSIWYG エディタで編集', 'label': 'リッチテキスト'}), 1: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': '<small>タグなどHTMLを直接入力（上級者向け）', 'label': 'HTML直接入力'})}, verbose_name='送信完了メッセージ'),
        ),
    ]
