# Generated by Django 5.2.6 on 2025-10-05 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: DMM FX, GMOクリック証券', max_length=100, verbose_name='証券会社名')),
                ('logo', models.URLField(blank=True, help_text='証券会社のロゴ画像URL（将来的に画像アップロードに変更予定）', verbose_name='ロゴURL')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='証券会社の特徴（最大5個推奨）', size=None, verbose_name='特徴')),
                ('bonus', models.CharField(blank=True, help_text='例: 新規口座開設で最大30万円', max_length=200, verbose_name='ボーナス情報')),
                ('cta_url', models.URLField(help_text='口座開設ページのURL（アフィリエイトリンク）', verbose_name='アフィリエイトURL')),
                ('tracking_id', models.CharField(help_text='A/Bテスト用ID（例: asp-dmm-fx-001）', max_length=50, unique=True, verbose_name='トラッキングID')),
                ('rank', models.IntegerField(default=0, help_text='数字が小さいほど上位に表示（1位=1, 2位=2, ...）', verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, help_text='チェックを外すと非表示になります', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ASP証券会社',
                'verbose_name_plural': 'ASP証券会社',
                'ordering': ['rank', '-created_at'],
                'indexes': [models.Index(fields=['rank', 'is_active'], name='asp_broker_rank_aac6fb_idx'), models.Index(fields=['is_active', '-created_at'], name='asp_broker_is_acti_826ca9_idx')],
            },
        ),
    ]
