# Generated by Django 5.2.6 on 2025-10-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASPAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='管理用の名前（例: DMM FX 新規口座開設キャンペーン 2025/10）', max_length=200, verbose_name='広告名')),
                ('ad_code', models.TextField(help_text='A8.netなどのASPからコピーしたHTMLタグをそのまま貼り付けてください', verbose_name='広告コード')),
                ('placement', models.CharField(choices=[('homepage-hero', 'トップページ ヒーロー'), ('homepage-middle', 'トップページ 中盤'), ('homepage-bottom', 'トップページ 下部'), ('blog-toc', 'ブログ 目次後'), ('blog-middle', 'ブログ 中盤'), ('blog-bottom', 'ブログ 記事末尾'), ('tool-detail-top', 'ツール詳細 上部'), ('tool-detail-bottom', 'ツール詳細 下部'), ('sidebar-top', 'サイドバー 上部'), ('sidebar-bottom', 'サイドバー 下部'), ('list-infeed', '一覧ページ インフィード')], db_index=True, help_text='広告を表示する場所を選択', max_length=50, verbose_name='配置場所')),
                ('start_date', models.DateTimeField(blank=True, help_text='この日時から広告を表示（未設定の場合は即時表示）', null=True, verbose_name='開始日時')),
                ('end_date', models.DateTimeField(blank=True, help_text='この日時で広告を自動停止（未設定の場合は無期限）', null=True, verbose_name='終了日時')),
                ('priority', models.IntegerField(default=1, help_text='数字が小さいほど優先表示（1が最優先）', verbose_name='優先度')),
                ('weight', models.IntegerField(default=10, help_text='ランダム表示時の出現確率（1-100）', verbose_name='重み')),
                ('impressions', models.IntegerField(default=0, editable=False, help_text='広告が表示された回数', verbose_name='表示数（Impression）')),
                ('clicks', models.IntegerField(default=0, editable=False, help_text='広告がクリックされた回数', verbose_name='クリック数（Click）')),
                ('is_active', models.BooleanField(default=True, help_text='チェックを外すと非表示になります', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ASP広告',
                'verbose_name_plural': 'ASP広告',
                'ordering': ['placement', 'priority', '-weight'],
                'indexes': [models.Index(fields=['placement', 'is_active', 'priority'], name='asp_aspad_placeme_1323e7_idx'), models.Index(fields=['is_active', 'start_date', 'end_date'], name='asp_aspad_is_acti_463318_idx')],
            },
        ),
    ]
