# Generated by Django 5.2.6 on 2025-12-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspad',
            name='placement',
            field=models.CharField(choices=[('homepage-middle', 'トップページ 中盤（ASP）'), ('sidebar-top', 'サイドバー ランキング直後（ASP）'), ('tool-detail-bottom', 'ツール詳細 下部（ASP）'), ('tool-detail-middle', 'ツール詳細 中盤（AdSense）'), ('homepage-bottom', 'トップページ 下部（AdSense）')], db_index=True, help_text='広告を表示する場所を選択', max_length=50, verbose_name='配置場所'),
        ),
    ]
