# Generated by Django 5.2.6 on 2025-10-01 03:24

import django.contrib.postgres.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ツールの名前', max_length=200, verbose_name='ツール名')),
                ('slug', models.SlugField(help_text='URL用（自動生成されます）', unique=True, verbose_name='スラッグ')),
                ('short_description', models.TextField(help_text='一覧表示用の短い説明（100文字以内）', max_length=100, verbose_name='短い説明')),
                ('long_description', models.TextField(blank=True, help_text='詳細ページ用の説明（HTMLまたはMarkdown）', verbose_name='詳細説明')),
                ('platform', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mt4', 'MetaTrader 4'), ('mt5', 'MetaTrader 5'), ('tradingview', 'TradingView')], max_length=20), help_text='対応プラットフォーム（複数選択可）', size=None, verbose_name='プラットフォーム')),
                ('tool_type', models.CharField(choices=[('EA', 'EA（自動売買）'), ('Indicator', 'インジケーター'), ('Library', 'ライブラリ'), ('Script', 'スクリプト'), ('Strategy', 'ストラテジー')], help_text='ツールの種類', max_length=20, verbose_name='ツールタイプ')),
                ('price_type', models.CharField(choices=[('free', '無料'), ('paid', '有料'), ('freemium', 'フリーミアム')], default='free', help_text='価格体系', max_length=20, verbose_name='価格タイプ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='有料の場合の価格（USD）', max_digits=10, null=True, verbose_name='価格')),
                ('ribbons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='例: new, featured, popular', size=None, verbose_name='リボン')),
                ('image_url', models.URLField(help_text='サムネイル画像のURL', verbose_name='画像URL')),
                ('external_url', models.URLField(help_text='ダウンロード/販売ページのURL', verbose_name='外部URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='開発者、バージョン、最終更新日等', verbose_name='メタデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='関連するタグ', through='tags.TaggedItem', to='tags.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'ツール',
                'verbose_name_plural': 'ツール',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool_type'], name='tools_tool_tool_ty_ce1bbe_idx'), models.Index(fields=['price_type'], name='tools_tool_price_t_89e657_idx'), models.Index(fields=['-created_at'], name='tools_tool_created_1fd619_idx')],
            },
        ),
    ]
