# Generated by Django 5.2.6 on 2025-10-02 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolStats',
            fields=[
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='tools.tool', verbose_name='ツール')),
                ('week_views', models.IntegerField(default=0, help_text='直近7日間のページビュー数', verbose_name='週間PV数')),
                ('week_shares', models.IntegerField(default=0, help_text='直近7日間のSNSシェア数', verbose_name='週間シェア数')),
                ('week_avg_duration', models.FloatField(default=0.0, help_text='直近7日間の平均滞在時間（秒）', verbose_name='週間平均滞在時間')),
                ('week_score', models.FloatField(db_index=True, default=0.0, help_text='WeeklyScore = (週間PV × 0.5) + (平均滞在時間 ÷ 10 × 0.3) + (週間シェア数 × 2)', verbose_name='週間スコア')),
                ('current_rank', models.IntegerField(blank=True, help_text='現在の週間順位（1〜50）', null=True, verbose_name='現在の順位')),
                ('prev_week_rank', models.IntegerField(blank=True, help_text='前週の順位（順位変動計算用）', null=True, verbose_name='前週順位')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': 'ツール統計',
                'verbose_name_plural': 'ツール統計',
                'ordering': ['-week_score'],
                'indexes': [models.Index(fields=['-week_score'], name='idx_week_score'), models.Index(fields=['current_rank'], name='idx_current_rank')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'ページビュー'), ('duration', '滞在時間'), ('share', 'シェア')], max_length=20, verbose_name='イベント種別')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='10秒以上のみ有効', null=True, verbose_name='滞在時間（秒）')),
                ('share_platform', models.CharField(blank=True, choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('line', 'LINE'), ('copy', 'URLコピー')], max_length=20, null=True, verbose_name='シェアプラットフォーム')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Bot判定用', null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, help_text='Bot判定用', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='記録日時')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tools.tool', verbose_name='ツール')),
            ],
            options={
                'verbose_name': 'イベントログ',
                'verbose_name_plural': 'イベントログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tool', '-created_at'], name='idx_tool_created'), models.Index(fields=['event_type', '-created_at'], name='idx_event_created')],
            },
        ),
    ]
