# Generated by Django 5.2.6 on 2025-10-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolstats_eventlog'),
    ]

    operations = [
        # フィールド型変更のみ（Djangoが自動でデータ変換）
        migrations.AlterField(
            model_name='tool',
            name='platform',
            field=models.CharField(
                choices=[
                    ('mt4', 'MetaTrader 4'),
                    ('mt5', 'MetaTrader 5'),
                    ('tradingview', 'TradingView')
                ],
                help_text='対応プラットフォーム',
                max_length=20,
                verbose_name='プラットフォーム'
            ),
        ),
    ]
