# Generated by Django 5.2.6 on 2025-12-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolstats',
            name='week_clicks',
            field=models.IntegerField(default=0, help_text='直近7日間の外部リンククリック数', verbose_name='週間CTAクリック数'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('view', 'ページビュー'), ('duration', '滞在時間'), ('share', 'シェア'), ('click', 'CTAクリック')], max_length=20, verbose_name='イベント種別'),
        ),
        migrations.AlterField(
            model_name='toolstats',
            name='week_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='WeeklyScore = (CTAクリック × 5) + (シェア × 2) + (滞在時間 ÷ 10 × 0.5) + (PV × 0.3)', verbose_name='週間スコア'),
        ),
    ]
