# Generated by Django 5.2.6 on 2025-12-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_add_week_clicks_and_click_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='price',
        ),
    ]
