# Generated by Django 5.2.6 on 2025-12-15 11:42

from django.db import migrations, models


# Generated by Django 5.2.6 on 2025-12-15 11:42

import unicodedata
import re
from django.db import migrations, models


def normalize_name(name):
    """名前を正規化して比較可能な形式に変換"""
    if not name:
        return ""
    
    # 1. Unicode正規化（全角→半角）
    normalized = unicodedata.normalize('NFKC', name)
    
    # 2. 小文字化
    normalized = normalized.lower()
    
    # 3. 空白の統一（連続空白→単一空白、前後trim）
    normalized = re.sub(r'\s+', ' ', normalized).strip()
    
    # 4. 特殊文字除去（英数字、日本語、空白のみ残す）
    normalized = re.sub(r'[^\w\s\u3040-\u309f\u30a0-\u30ff\u4e00-\u9fff]', '', normalized)
    
    return normalized


def populate_normalized_names(apps, schema_editor):
    """既存ツールのnormalized_nameを設定"""
    Tool = apps.get_model('tools', 'Tool')
    for tool in Tool.objects.all():
        tool.normalized_name = normalize_name(tool.name)
        tool.save(update_fields=['normalized_name'])


def reverse_populate(apps, schema_editor):
    """リバース操作（空文字に戻す）"""
    Tool = apps.get_model('tools', 'Tool')
    Tool.objects.all().update(normalized_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tagmapping_alter_tag_category_alter_tag_synonyms'),
        ('tools', '0005_remove_price_field'),
    ]

    operations = [
        # 1. normalized_nameフィールドを追加
        migrations.AddField(
            model_name='tool',
            name='normalized_name',
            field=models.CharField(blank=True, editable=False, help_text='重複チェック用（自動生成）', max_length=200, verbose_name='正規化名'),
        ),
        # 2. external_urlをユニークに変更
        migrations.AlterField(
            model_name='tool',
            name='external_url',
            field=models.URLField(help_text='ダウンロード/販売ページのURL（重複登録不可）', unique=True, verbose_name='外部URL'),
        ),
        # 3. 既存データのnormalized_nameを設定
        migrations.RunPython(populate_normalized_names, reverse_populate),
        # 4. インデックスを追加
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['normalized_name'], name='tools_tool_normali_523d2d_idx'),
        ),
        # 5. ユニーク制約を追加
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'platform'), name='unique_tool_per_platform'),
        ),
    ]
