# Generated by Django 5.2.6 on 2025-12-17 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_add_duplicate_prevention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: トレンドフォロー、リスク管理', max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(help_text='URL用（自動生成されます）', unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, help_text='このカテゴリの説明（SEO用メタディスクリプション）', verbose_name='説明')),
                ('icon', models.CharField(blank=True, help_text='FontAwesomeアイコン名（例: fa-chart-line）', max_length=50, verbose_name='アイコン')),
                ('order', models.IntegerField(default=0, help_text='小さい数字ほど上に表示されます', verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'ツールカテゴリ',
                'verbose_name_plural': 'ツールカテゴリ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(blank=True, help_text='ツールの用途カテゴリ（SEO・検索用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.toolcategory', verbose_name='カテゴリ'),
        ),
    ]
