# Generated by Django 5.2.6 on 2025-12-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_add_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image_error_message',
            field=models.TextField(blank=True, help_text='画像取得エラー時のメッセージ', verbose_name='エラーメッセージ'),
        ),
        migrations.AddField(
            model_name='tool',
            name='image_last_checked',
            field=models.DateTimeField(blank=True, help_text='画像URLを最後にチェックした日時', null=True, verbose_name='最終チェック日時'),
        ),
        migrations.AddField(
            model_name='tool',
            name='image_status',
            field=models.CharField(choices=[('ok', '正常'), ('error', 'エラー'), ('unchecked', '未チェック')], default='unchecked', help_text='画像URLの有効性チェック結果', max_length=20, verbose_name='画像ステータス'),
        ),
    ]
