# Generated by Django 5.2.6 on 2025-12-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_add_image_status_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='category',
        ),
        migrations.DeleteModel(
            name='ToolCategory',
        ),
    ]
