# Generated by Django 5.2.6 on 2025-10-01 07:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('tools', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 初心者ガイド、ツールレビュー', max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(help_text='URL用（自動生成されます）', unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, help_text='このカテゴリの説明（任意）', verbose_name='説明')),
                ('order', models.IntegerField(default=0, help_text='小さい数字ほど上に表示されます', verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'ブログカテゴリ',
                'verbose_name_plural': 'ブログカテゴリ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='ブログトップページに表示される説明文', verbose_name='イントロダクション')),
            ],
            options={
                'verbose_name': 'ブログインデックスページ',
                'verbose_name_plural': 'ブログインデックスページ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: FX、株式、仮想通貨', max_length=100, unique=True, verbose_name='投資タイプ名')),
                ('slug', models.SlugField(help_text='URL用（自動生成されます）', unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, help_text='この投資タイプの説明（任意）', verbose_name='説明')),
                ('order', models.IntegerField(default=0, help_text='小さい数字ほど上に表示されます', verbose_name='表示順')),
            ],
            options={
                'verbose_name': '投資タイプ',
                'verbose_name_plural': '投資タイプ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.TextField(help_text='記事の要約（検索結果・SNSシェア用、最大200文字）', max_length=200, verbose_name='抜粋')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('heading', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr'], 'help_text': '本文の段落', 'label': '段落'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'セクション見出し', 'label': '見出し'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': '記事内の画像', 'label': '画像'})})),
                ('view_count', models.IntegerField(default=0, editable=False, help_text='この記事の閲覧数（自動カウント）', verbose_name='閲覧数')),
                ('category', models.ForeignKey(help_text='記事のカテゴリを選択', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_pages', to='blog.blogcategory', verbose_name='カテゴリ')),
                ('featured_image', models.ForeignKey(blank=True, help_text='記事のアイキャッチ画像（推奨: 1200×630px）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='アイキャッチ画像')),
                ('related_tools', models.ManyToManyField(blank=True, help_text='この記事で紹介するツール', to='tools.tool', verbose_name='関連ツール')),
                ('tags', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='記事に関連するタグ（既存タグから選択）', to='tags.tag', verbose_name='タグ')),
                ('investment_type', models.ForeignKey(help_text='記事が扱う投資タイプを選択', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_pages', to='blog.investmenttype', verbose_name='投資タイプ')),
            ],
            options={
                'verbose_name': 'ブログ記事',
                'verbose_name_plural': 'ブログ記事',
            },
            bases=('wagtailcore.page',),
        ),
    ]
