# Generated by Django 5.2.6 on 2025-10-01 07:45

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='related_tools',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='この記事で紹介するツール', to='tools.tool', verbose_name='関連ツール'),
        ),
    ]
