# Generated by Django 5.2.6 on 2025-12-11 04:13
# Manually modified for M2M field migration

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpage_body'),
        ('tags', '0002_tagmapping_alter_tag_category_alter_tag_synonyms'),
    ]

    operations = [
        # Step 1: 旧tagsフィールド（ParentalManyToManyField）を削除
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        # Step 2: BlogPageTag中間モデルを作成
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_blogs', to='tags.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        # Step 3: 新tagsフィールド（ClusterTaggableManager）を追加
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='記事に関連するタグ（入力で候補表示、既存タグから選択）', through='blog.BlogPageTag', to='tags.Tag', verbose_name='タグ'),
        ),
    ]
