# Generated by Django 5.2.6 on 2025-10-29 00:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(help_text='統一されるタグ名（例: ボリンジャーバンド）', max_length=100, unique=True, verbose_name='正式名称')),
                ('variations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='カンマ区切りで入力（例: bb,ｂｂ,ボリバン,Bollinger Bands）', size=None, verbose_name='表記バリエーション')),
                ('category', models.CharField(choices=[('technical_indicator', 'テクニカル指標'), ('trade_style', '取引スタイル'), ('currency_pair', '通貨ペア'), ('strategy_type', '戦略タイプ')], default='technical_indicator', max_length=30, verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': 'タグマッピング',
                'verbose_name_plural': 'タグマッピング',
                'ordering': ['category', 'canonical_name'],
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('technical_indicator', 'テクニカル指標'), ('trade_style', '取引スタイル'), ('currency_pair', '通貨ペア'), ('strategy_type', '戦略タイプ')], help_text='タグのカテゴリ', max_length=30, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='自動的に収集された表記ゆれ', size=None, verbose_name='表記ゆれ'),
        ),
    ]
