# Generated by Django 5.2.6 on 2025-12-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tagmapping_alter_tag_category_alter_tag_synonyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='表示用のカテゴリ名（例: テクニカル指標）', max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(help_text='URL・コード用の識別子（例: technical_indicator）', max_length=30, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, help_text='カテゴリの説明（任意）', verbose_name='説明')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='小さい順に表示', verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'タグカテゴリ',
                'verbose_name_plural': 'タグカテゴリ',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
