# Generated by Django 5.2.6 on 2025-12-21 06:00

from django.db import migrations


def populate_tag_categories(apps, schema_editor):
    """初期カテゴリデータを投入"""
    TagCategory = apps.get_model('tags', 'TagCategory')
    
    categories = [
        {'name': 'テクニカル指標', 'slug': 'technical_indicator', 'display_order': 1},
        {'name': '取引スタイル', 'slug': 'trade_style', 'display_order': 2},
        {'name': '通貨ペア', 'slug': 'currency_pair', 'display_order': 3},
        {'name': '戦略タイプ', 'slug': 'strategy_type', 'display_order': 4},
    ]
    
    for cat_data in categories:
        TagCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults={
                'name': cat_data['name'],
                'display_order': cat_data['display_order'],
            }
        )


def reverse_populate(apps, schema_editor):
    """ロールバック時にカテゴリを削除"""
    TagCategory = apps.get_model('tags', 'TagCategory')
    TagCategory.objects.filter(slug__in=[
        'technical_indicator', 'trade_style', 'currency_pair', 'strategy_type'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_add_tagcategory'),
    ]

    operations = [
        migrations.RunPython(populate_tag_categories, reverse_populate),
    ]
