# Generated by Django 5.2.6 on 2025-12-21 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_populate_tagcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_category__display_order', 'name'], 'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_category',
            field=models.ForeignKey(blank=True, help_text='タグのカテゴリ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='tags.tagcategory', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('technical_indicator', 'テクニカル指標'), ('trade_style', '取引スタイル'), ('currency_pair', '通貨ペア'), ('strategy_type', '戦略タイプ')], help_text='※廃止予定：tag_categoryを使用', max_length=30, verbose_name='カテゴリ（旧）'),
        ),
    ]
