# Generated by Django 5.2.6 on 2025-12-21

from django.db import migrations


def migrate_category_to_fk(apps, schema_editor):
    """既存のcategory CharFieldの値をtag_category FKに変換"""
    Tag = apps.get_model('tags', 'Tag')
    TagCategory = apps.get_model('tags', 'TagCategory')
    
    # カテゴリのマッピングを作成（slug -> TagCategory）
    category_map = {}
    for cat in TagCategory.objects.all():
        category_map[cat.slug] = cat
    
    # 各タグのcategory値をtag_category FKに変換
    for tag in Tag.objects.all():
        if tag.category and tag.category in category_map:
            tag.tag_category = category_map[tag.category]
            tag.save()


def reverse_migrate(apps, schema_editor):
    """ロールバック: tag_category FKの値をcategory CharFieldに戻す"""
    Tag = apps.get_model('tags', 'Tag')
    
    for tag in Tag.objects.filter(tag_category__isnull=False):
        tag.category = tag.tag_category.slug
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_add_tag_category_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_category_to_fk, reverse_migrate),
    ]
