# Generated by Django 5.2.6 on 2025-12-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_migrate_category_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
